### ISSUE TITLE
Replace 'verbosity' with logging level

### ISSUE THREAD

**Issue by connollyst** [numenta/htm.java#146]
We currently pass around a ``verbosity`` variable to determine how much output, if any, should be printed.

Instead, we should log with appropriate logging levels and leverage the logger to print or not.

verbosity 2 would be ``logger.debug()``
verbosity 1 would be ``logger.info()``

Normal runtime setting would be with ``warn`` or ``error`` levels.

Depends on #145.

**Comment by solovyevk** [comment]
+1 on this. We need logging library.Verbosity variable is python code legacy.
I would like to use log4j + commons-logging

**Comment by sambitgaan** [comment]
Absolutely, +1 from me.
Yes for, log4j + commons-logging

**Comment by connollyst** [comment]
Great. Here's my 2¢ regarding what to change..

Logging Interface
-----------------------
I'd actually suggest [SLF4J](http://www.slf4j.org/) as much as possible. It's not a logging _implementation_, but a logging _interface_/facade. By using this for the core, we enable the end users (developers) to drop in whichever logging implementation they want.

That is, if I use ``htm.java`` in my desktop application I can drop in ``Log4J``, when I use ``htm.java`` in an Android app I'll use the [``andoid-logger``](https://github.com/noveogroup/android-logger), etc.

I believe SLF4J is the industry standard for any reusable library as it imposes no implementation details on the end user of the library.


Logging Implementation
--------------------------------
There are surely cases in our code where we'll need a logging _implementation_. I'm not very familiar with the code base yet, but at a very minimum we'll want a logging implementation in our unit tests.

If we have the pick of the litter, I would favor [Logback](http://logback.qos.ch/) which is developed by the Log4J folks and intended as a successor project.


Logging "Verbosity"
--------------------------
Just to be clear, what levels of 'verbosity' are used in the Python project and how should they be translated to standard logging levels. We have:
``FATAL``
``ERROR``
``WARN``
``INFO``
``DEBUG``
``TRACE``
``TRACE`` with an integer level

I don't think we need to bring the last one/two into the picture, ``INFO`` and ``DEBUG`` are probably enough to work with.

Can someone more familiar with the project comment on this mapping from verbosity to logging level?


Cheers,
Sean

**Comment by cogmission** [comment]
Agreed. Let's give "Logback" a try.

I'm creating smaller "bite size" chunks out of this issue so that we can get more traction on this. Closing this and creating a GIST here: https://gist.github.com/cogmission/bcc0b54aaf39b6b0108d so that Sean's helpful comments can be referenced.

**Comment by cogmission** [comment]
Ok, I've created specific issues for individual classes that use the old Python verbosity method. I also noticed that SparsePassThroughEncoder, PassThroughEncoder, MultiEncoder, and LogEncoder don't use any logging method at all. These should also do sanity checks etc. so we should work on getting logging implemented in these as well.
