### ISSUE TITLE
Verbosity Replacement: Encoder.java

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#150]
The Encoder class would benefit from the substitution of the "Verbosity" setting with an actual logging framework. Let's use Logback found here: http://logback.qos.ch/download.html as the actual logging framework. As a result, the log back jar(s) will need to be added to the build.gradle file and the pom.xml file. 

For more information, please refer to the this information: https://gist.github.com/cogmission/bcc0b54aaf39b6b0108d

**Comment by connollyst** [comment]
Hey David, is there a reason to use Logback rather than SLF4J? I feel the latter would keep end users' options more open.

**Comment by cogmission** [comment]
Isn't that the implementation of the Logging API you yourself suggested? :)

**Comment by connollyst** [comment]
For sure, but in the code itself we wouldn't use any logging _implementation_. Instead we would just code to the interface/facade, which [feels the same](https://github.com/connollyst/htm.java/blob/logging/src/main/java/org/numenta/nupic/encoders/RandomDistributedScalarEncoder.java#L376) but isn't backed by any real logging.

When someone builds an application on ``htm.java`` they don't get any logging from us unless they have a logging mechanism in place themselves (like Logback or Log4J). When they drop one in, then they get logging from us - and configure the level.

So for this ticket, we wouldn't need/want Logback.

If we provide examples or want logging in our tests, we can add Logback there.


All that said.. I'm the new guy! lol
I'm in no position to make decisions, just suggestions  =)

**Comment by cogmission** [comment]
So in other words, because the tests *ARE* downstream
clients/implementations, we *DO* in fact need the Logback library?

We need to consider the *whole* distribution, not only the specific issue
regarding this, so the entire solution would have to include both the SLF4J
libs and the Logback libs - I believe this is correct?



On Sun, Jan 18, 2015 at 12:22 PM, Sean Connolly <notifications@github.com>
wrote:

> For sure, but in the code itself we wouldn't use any logging
> *implementation*. Instead we would just code to the interface/facade,
> which feels the same
> <https://github.com/connollyst/htm.java/blob/logging/src/main/java/org/numenta/nupic/encoders/RandomDistributedScalarEncoder.java#L376>
> but isn't backed by any real logging.
>
> When someone builds an application on htm.java they don't get any logging
> from us unless they have a logging mechanism in place themselves (like
> Logback or Log4J). When they drop one in, then they get logging from us -
> and configure the level.
>
> So for this ticket, we wouldn't need/want Logback.
>
> If we provide examples or want logging in our tests, we can add Logback
> there.
>
> All that said.. I'm the new guy! lol
> I'm in no position to make decisions, just suggestions =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/150#issuecomment-70419027>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by connollyst** [comment]
Continued in #154
