### ISSUE TITLE
Verbosity Replacement: SDRCategoryEncoder

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#154]
The SDRCategoryEncoder class would benefit from the substitution of the "Verbosity" setting with an actual logging framework. Let's use Logback found here: http://logback.qos.ch/download.html as the actual logging framework. As a result, the log back jar(s) will need to be added to the build.gradle file and the pom.xml file. 

For more information, please refer to the this information: https://gist.github.com/cogmission/bcc0b54aaf39b6b0108d

**Comment by solovyevk** [comment]
Hi David,

Please assign this one to me.

Thanks,

Kirill

**Comment by cogmission** [comment]
Roger that, Thanks Krill!

On Sun, Jan 18, 2015 at 8:28 AM, Kirill <notifications@github.com> wrote:

> Hi David,
>
> Please assign this one to me.
>
> Thanks,
>
> Kirill
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/154#issuecomment-70410157>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by cogmission** [comment]
So since you are the first one, you will also have to introduce the Logback
libraries into the repo, ok?

On Sun, Jan 18, 2015 at 8:36 AM, cogmission1 . <cognitionmission@gmail.com>
wrote:

> Roger that, Thanks Krill!
>
> On Sun, Jan 18, 2015 at 8:28 AM, Kirill <notifications@github.com> wrote:
>
>> Hi David,
>>
>> Please assign this one to me.
>>
>> Thanks,
>>
>> Kirill
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/numenta/htm.java/issues/154#issuecomment-70410157>.
>>
>
>
>
> --
> *We find it hard to hear what another is saying because of how loudly "who
> one is", speaks...*
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by solovyevk** [comment]
David,

Sure I will add Logback  libraries. Do you want to add binaries under libs as  usual?

Kirill.

**Comment by cogmission** [comment]
Yes, please. I believe though that you should reference (and also use) SLF4J and it's API so that we can have heterogenous code that anyone can use to plugin they're own Logging implementation. So, you would have to bring in both I believe, though I'm not sure. see here: https://github.com/numenta/htm.java/issues/150#issuecomment-70418674

See the last part of this conversation. I haven't yet investigated whether to use Logback underneath SLF4J API's we would need to bring in both? Maybe @connollyst (Sean Connolly) can clear this up?

**Comment by connollyst** [comment]
Sure.

If I were developing a reusable library, I'd use SLF4J. When I need logging, I'd use Logback.
Say I want logging in my tests, in Maven this would look like:

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.10</version>
    </dependency>
    <dependency>
	<groupId>ch.qos.logback</groupId>
	<artifactId>logback-classic</artifactId>
	<version>1.1.2</version>
        <scope>test</scope>
    </dependency>

When someone uses our library, they aren't bound to Logback as it's only a ``test`` scoped dependency.

Hope that clears up what I was suggesting.

**Comment by connollyst** [comment]
From @cogmission in #150:

> So in other words, because the tests *ARE* downstream clients/implementations, we *DO* in fact need the Logback library?

Exactly.

> We need to consider the *whole* distribution, not only the specific issue regarding this, so the entire solution would have to include both the SLF4J libs and the Logback libs - I believe this is correct?

I'm not sure I follow, but I think I'm behind on how exactly the ``htm.java`` distribution is intended to be used.

If it is always meant to be _used_ as part of another project, I'd leave Logback out of our distribution. This way your choice of logger doesn't impose on the end user. However, if it is meant to be _run_ as a standalone tool, then you'd want to provide some form of logging implementation.

**Comment by connollyst** [comment]
PS: I hadn't noticed the ``libs/`` directory, is it not obviated by Gradle & Maven?

**Comment by cogmission** [comment]
>
> PS: I hadn't noticed the libs/ directory, is it not obviated by Gradle &
> Maven?


The "libs" directory is there so we don't force Gradle or Maven down
anyone's throat. I like simplicity, and I hate when I have to download the
entire Library of Congress just to use a simple library. (which is a shiver
runs down my spine when I see the word "Apache" :)  )

I'm not sure I follow, but I think I'm behind on how exactly the
htm.java distribution
> is intended to be used.
> If it is always meant to be *used* as part of another project, I'd leave
> Logback out of our distribution. This way your choice of logger doesn't
> impose on the end user. However, if it is meant to be *run* as a
> standalone tool, then you'd want to provide some form of logging
> implementation.


It will be used in both ways, though it really isn't a standalone tool. We
should add SLF4J which allows you to bind directly to any logging library,
and add Logback to the libs directory (for tests). I did some research on
the different libraries to catch up on what the current thinking is (since
JSR 47), if you're interested you can read this:
http://java.dzone.com/articles/shouldn’t-we-standardize-java

Anyway, here's what we should/can do. We can add a direct dependency on
slf4j (in gradle build file and maven pom file) and also add the dependency
to Logback in the corresponding test dependency sections, and then add the
jars to the libs directory.

Make sense?

David

On Sun, Jan 18, 2015 at 12:43 PM, Sean Connolly <notifications@github.com>
wrote:

> PS: I hadn't noticed the libs/ directory, is it not obviated by Gradle &
> Maven?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/154#issuecomment-70419838>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by connollyst** [comment]
Sounds good to me!
I have this done on my fork so can merge it in once [my other pull request](https://github.com/numenta/htm.java/pull/158) goes though.

**Comment by cogmission** [comment]
Yep I saw it ;)

I'll get to it before tomorrow ok? Thank you for your contribution!



On Sun, Jan 18, 2015 at 1:10 PM, Sean Connolly <notifications@github.com>
wrote:

> Sounds good to me!
> I have this done on my fork so can merge it in once my other pull request
> <https://github.com/numenta/htm.java/pull/158> goes though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/154#issuecomment-70420901>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by solovyevk** [comment]
@connollyst I see you start on logging here https://github.com/connollyst/htm.java/tree/logging.
I'll wait for your merge to complete #154

Thank You,

Kirill.

**Comment by cogmission** [comment]
@solovyevk, @connollyst I think we got "stalled" with the logging effort because Kirill was waiting on the logging completion to be done by Sean in parallel with his work on the encoder. There was confusion about who was working on what encoder, and it got resolved by some collaboration between @connollyst  and @anubhavchaturvedi. 

So Kirill, the logging work Sean had started on never got merged back in to the main trunk - so I think you are free to start on the whole thing -or- if Sean still wants to work on this then he can do that and I can make an "issue" to have the groundwork be laid by Sean. 

In either case, guys let's not let this go for too long without some kind of resolution?

**Comment by solovyevk** [comment]
@cogmission,@connollyst I just see Sean already has logging integrated in dedicated branch https://github.com/connollyst/htm.java/tree/logging. 

David,

If it is not going to be merge I can introduce logging framework very quick, but I'd rather use log4j since I used it before in other projects :)

**Comment by cogmission** [comment]
@connollyst Already did this one, I haven't looked until now. @solovyevk  I'm Closing.
