### ISSUE TITLE
SparsePassThroughEncoder, PassThroughEncoder, MultiEncoder, LogEncoder and GeospatialCoordinateEncoder don't use any logging method

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#156]
This is an issue to create specific issues :)

We should create individual issues for these. Anybody can feel free to create these issues. Use the other logging issues for reference. I can't do this right now, but I'll get back to it if no one else does it.

**Comment by cogmission** [comment]
Adding GeospatialCoordinateEncoder to this list...

**Comment by antidata** [comment]
Hey @cogmission I would like to contribute. Are you expecting to get something similar to the logger used here https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java ?

**Comment by cogmission** [comment]
Hi @antidata,

Sure, I believe the ScalarEncoder can be used as an example of possible points where logging can be introduced into the code. The ScalarEncoder itself should probably have an "if" branch around the series calls to Logger.TRACE that are high in numbers there to keep from slowing down the code - but we can talk about that...

Any place you would like to "jump in" would be nice - I haven't yet broken out each Encoder subclass into an issue to introduce logging to - so I can do that if you would like to "pick" one and work on it? 

I will go ahead and break these out into individual "issues" that will be more manageable to work on...
 Just let me know?

**Comment by antidata** [comment]
Sounds good!

**Comment by cogmission** [comment]
@antidata 

I will break these out into smaller issues right now, and then I'll announce the completion of that task by making an issue to make these issues, and then closing it. Following that, you can "pick" one by commenting on it - saying you'd like to work on it. And I will assign it to you.

**Comment by cogmission** [comment]
Actually, I will just close "this" issue to announce the issues being broken out...

**Comment by cogmission** [comment]
We could review the rest of the Encoders to verify that proper logging exists... but I think that about does it? Closing this to indicate that tasks have been broken out.

**Comment by cogmission** [comment]
Ok done. Pick one by responding to this email?

On Fri, Mar 20, 2015 at 5:40 PM, antidata <notifications@github.com> wrote:

> Sounds good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/156#issuecomment-84171245>.
>



-- 
Mit freundlichen Grüßen,
*With kind regards,*

David Ray
Java Solutions Architect
*cortical.io <http://cortical.io> GmbH*
sponsor of:  HTM.java (open source) <https://github.com/numenta/htm.java>
Mariahilferstrasse 4, 1070 Vienna, Austria
d.ray@cortical.io
http://cortical.io

**Comment by antidata** [comment]
Ok Thanks, I'll start with SparsePassThroughEncoder

**Comment by cogmission** [comment]
Cool! I will assign that on over...

On Fri, Mar 20, 2015 at 5:59 PM, antidata <notifications@github.com> wrote:

> Ok Thanks, I'll start with SparsePassThroughEncoder
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/156#issuecomment-84176409>.
>



-- 
Mit freundlichen Grüßen,
*With kind regards,*

David Ray
Java Solutions Architect
*cortical.io <http://cortical.io> GmbH*
sponsor of:  HTM.java (open source) <https://github.com/numenta/htm.java>
Mariahilferstrasse 4, 1070 Vienna, Austria
d.ray@cortical.io
http://cortical.io
