### ISSUE TITLE
Improvement for the Eclipse Environment Setup Wiki

### ISSUE THREAD

**Issue by chessweb01** [numenta/htm.java#175]
In order to build htm.java one has to install the joda-time plugin. Copy joda-time-2.x.jar into the folder eclipse/plugins and add the jar to the Java build path (libraries). This ought to be mentioned in the setup wiki.   

I installed joda-time 2.4 from http://sourceforge.net/projects/joda-time/files/joda-time/, but there seems to be a newer release on github: https://github.com/JodaOrg/joda-time/releases/tag/v2.7

**Comment by cogmission** [comment]
@chessweb01 Welcome!  :) Thanks for the warning. I had intended to add joda-time-2.5.jar to the libs directory for those who don't use gradle (recommended) or maven. The DateEncoder was just merged in to the trunk in the last couple of days, and we missed that.
