### ISSUE TITLE
Sync HTM.java Releases w/NuPIC

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#196]
The release numbering (in the grade.build and pom.xml files) and the Roadmap need to be updated with compatible numbering and sync'd up with the new release and Roadmap present in NuPIC. 

@rhyolight

**Comment by rhyolight** [comment]
Might be a lot of trouble to keep versions synced. Do you really think it's worth it?

**Comment by cogmission** [comment]
What I was thinking was that the htm.java version would always be the same as the version that most closely embodies the current state within NuPIC. At this point, with the resources available, I couldn't claim that it would keep up. 

Please advise because I have no experience with versioning and the excepted practices for version two related modules?

**Comment by rhyolight** [comment]
Versioning and releasing is not easy even without the constraint of keeping
synced with another project. My suggestion would be to forgo the version
number syncing and adopt your own versioning... just note in release notes
which NuPIC version your current release resembles.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
:+1: Sounds good, closing this...
