### ISSUE TITLE
CLAClassifier multiple steps may not be operating correctly

### ISSUE THREAD

**Issue by rengelking** [numenta/htm.java#199]
Hi David, I have been going through the QuickTest playing around, and I noticed that if I give the CLAClassifier steps 1 and 3,

`CLAClassifier classifier = new CLAClassifier(new TIntArrayList(new int[] { 1, 3 }), 0.1, 0.3, 0);`

when I read the result, the prob are all the same,
`CLAClassifier 3 step prob = [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]`.
 However, if I use CLACLassifier steps 1 and 2, I get accurate results for the next day and the day after that, and then if I use steps 1, 2 and 3, it then does T+3 correctly in the result:
`CLAClassifier 3 step prob = [0.0, 0.0, 0.0, 0.05043600632528007, 0.18487287595250435, 0.5283940413638714, 0.2362970763583443]`

Are all the intermediate steps required in the classifier if I want to get T+3, do I always need T+2, and T+1?

**Comment by cogmission** [comment]
Hi Ray,

Welcome! and thank you for your submission! I will take a look at it...

David

**Comment by cogmission** [comment]
Oops, we never closed this! This was resolved as a misunderstanding, I believe
