### ISSUE TITLE
SparsePassThroughEncoder requires the introduction of Logging

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#207]
Use the current logging library and method present in the ScalarEncoder as a "template" for the introduction of logging. This should include the corresponding unit test as well.

**Comment by antidata** [comment]
@cogmission I'll start with this one.

**Comment by cogmission** [comment]
@antidata @rhyolight I don't see you in the contributors list here - Have you filled out the contributor's license?

**Comment by cogmission** [comment]
@antidata Please indicate once you've filled this out: http://numenta.org/licenses/cl/

**Comment by cogmission** [comment]
Hi @antidata,

I'm still waiting for you to fill out the above contributor's license or acknowledge that you've previously filled it out? We can't really proceed until you fill that out (I can't assign issues to you, and we can't merge in any development work you might do). 

If you have any questions at all about the CL or our procedure, please feel free to ask me (either here or in a private email: cognitionmission@gmail.com)

**Comment by antidata** [comment]
@cogmission Done deal!

**Comment by cogmission** [comment]
@rhyolight  Please see

**Comment by antidata** [comment]
Hey @cogmission I'm on the contributors list now :)

**Comment by cogmission** [comment]
Hi @antidata !

@rhyolight I still don't see @antidata in the "Assignee" drop down list?

**Comment by rhyolight** [comment]
@cogmission That's because @antidata has not accepted our invitation to join the GitHub contributors team.

**Comment by antidata** [comment]
Cool. The invitation email ended up as Spam. It's now done. Thanks @rhyolight

**Comment by cogmission** [comment]
Thanks guys!  :+1:
