### ISSUE TITLE
PassThroughEncoder requires the introduction of Logging

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#208]
Use the current logging library and method present in the ScalarEncoder as a "template" for the introduction of logging. This should include the corresponding unit test as well.

**Comment by cogmission** [comment]
Assigning this to you @antidata 

For now, I'll just assign one at a time. Please keep in mind any new code paths created must have tests (by paths I mean methods).

**Comment by antidata** [comment]
I cannot edit labels @cogmission but sounds good
