### ISSUE TITLE
HTM.java should be registered & configured to upload to Maven Central

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#221]
To make the code available in useable form so that users can include htm.java in their projects via gradle or maven.

**Comment by rhyolight** [comment]
Do we want to upload to the archives on every build? Or manually when something is released?

**Comment by cogmission** [comment]
You know what, let's just do it manually when (or automatically) but just
on release?

On Mon, May 4, 2015 at 1:34 PM, Matthew Taylor <notifications@github.com>
wrote:

> Do we want to upload to the archives on every build? Or manually when
> something is released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/221#issuecomment-98806656>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by rhyolight** [comment]
That makes sense to me. So as long as someone [does this](https://github.com/numenta/htm.java/pull/220#discussion_r29609570) I think Travis will work.

**Comment by cogmission** [comment]
Ok then I believe you or I will have to have the configuration locally and just do a push  to maven central when we do a build on our local machines, otherwise we have to configure Travis to do it

**Comment by cogmission** [comment]
I can add that line that you suggested and test it locally so that Travis will do a build without errors. I will then have to get Peter to push that to his PR so we can merge is work?

**Comment by rhyolight** [comment]
Yes, or you could create a branch off his PR branch and submit a new PR.
