### ISSUE TITLE
Regarding #232, #238: Issue with CLAClassifier

### ISSUE THREAD

**Issue by chessweb01** [numenta/htm.java#243]
@cogmission , @scottpurdy , @rhyolight : I'm opening a new issue regarding #232 and #238 because I'm still certain that something is wrong with the CLAClassifier. To show this, I performed two experiments with the QuickTest.java example. In both cases memory resetting in on, but the reset doesn't happen on Monday like in David's original example (when encoder input is 1), but on Tuesday when the encoder input is two. 

What follows is the output for one week at the end of the run. For clarity, only the CLAClassifier 1 step prob estimation vector is shown:

===== Friday (5)  - Sequence Num: 9993 =====
CLAClassifier 1 step prob = [0.0, 6.379741262606635E-4, 0.11949919930277184, 0.07236243346291339, 0.10723947945601109, 0.4654668143369222, 0.23479409931512082]

===== Saturday (6)  - Sequence Num: 9994 =====
CLAClassifier 1 step prob = [0.0, 0.0, 0.04699326847118107, 0.07925728963220278, 0.12737230744026998, 0.31787611000453514, 0.42850102445181115]

===== Sunday (7)  - Sequence Num: 9995 =====
CLAClassifier 1 step prob = [0.0, 7.008279153790567E-4, 0.38242873844193537, 0.06645409864383159, 3.5125719859356163E-4, 0.3408358790136928, 0.20922919878656762]

===== Monday (1)  - Sequence Num: 9996 =====
CLAClassifier 1 step prob = [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]

===== Tuesday (2)  - Sequence Num: 9997 =====
CLAClassifier 1 step prob = [0.0, 0.002958799699708619, 0.5543985178923733, 0.10941383003562204, 0.06302677327965629, 0.20663496144615218, 0.06356711764648765]

===== Wednesday (3)  - Sequence Num: 9998 =====
CLAClassifier 1 step prob = [0.0, 6.997770016128778E-4, 0.13970182383232915, 0.388879563817466, 0.19178382804392421, 0.1536679359475725, 0.1252670713570953]

===== Thursday (4)  - Sequence Num: 9999 =====
CLAClassifier 1 step prob = [0.0, 8.174256277900919E-4, 0.08495637293955269, 0.19937685784961107, 0.2736845291808443, 0.23418366053949655, 0.20698115386270524]

Interpretation:
Fri: Prediction is Sat because CLAClassifier 1 step prob[5] is highest (OK)
Sat: Prediction is Sun because CLAClassifier 1 step prob[6] is highest (OK)
Sun: Prediction is Wed because CLAClassifier 1 step prob[2] is highest (???) Here CLAClassifier 1 step prob[0] should be highest, by the way, indicating a Monday prediction.
Mon: no prediction because of memory reset (OK)
Tue: prediction is Wed because CLAClassifier 1 step prob[2] is highest (OK)
Wed: prediction is Thu because CLAClassifier 1 step prob[3] is highest (OK)
Thu: prediction is Fri because CLAClassifier 1 step prob[4] is highest (OK)

Now, something is clearly off on Sunday besides the fact that CLAClassifier 1 step prob[0] which corresponds to a Monday prediction is always identical to zero.

Next comes the result of the same simulation with the proposed fix in CLAClassifier in place:

===== Friday (5)  - Sequence Num: 9993 =====
CLAClassifier 1 step prob = [0.1018582685665416, 5.194166304534105E-4, 0.09343736671099835, 0.07220078183251759, 0.10697339906760528, 0.4096101952232601, 0.21540057196862364]

===== Saturday (6)  - Sequence Num: 9994 =====
CLAClassifier 1 step prob = [0.0868107758161019, 0.0, 0.03532422510662751, 0.07907616501616949, 0.12705635305761778, 0.2915076051093348, 0.3802248758941485]

===== Sunday (7)  - Sequence Num: 9995 =====
CLAClassifier 1 step prob = [0.35342242840344673, 4.659442785036538E-4, 0.23054594501303238, 0.04243694293648137, 2.449002562973038E-4, 0.229419317118965, 0.14346452199327356]

===== Monday (1)  - Sequence Num: 9996 =====
CLAClassifier 1 step prob = [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]

===== Tuesday (2)  - Sequence Num: 9997 =====
CLAClassifier 1 step prob = [0.17535058491190322, 0.0028164005034243445, 0.45553646573889806, 0.09447698278764408, 0.06296246511297135, 0.16101501209560706, 0.04784208884955197]

===== Wednesday (3)  - Sequence Num: 9998 =====
CLAClassifier 1 step prob = [0.04116278241982905, 6.994468136874168E-4, 0.1208355083754605, 0.3674722610072709, 0.1915059809495113, 0.15334504307843908, 0.12497897735580193]

===== Thursday (4)  - Sequence Num: 9999 =====
CLAClassifier 1 step prob = [0.0016403899062704653, 8.168039514524062E-4, 0.08489176110821717, 0.1991087371996082, 0.2732621727614291, 0.23371821112273305, 0.20656192395028952]

As far as I can see, everything makes perfect sense now. In particular, on Sunday we have a prediction that Monday will be next because CLAClassifier 1 step prob[0] is highest.

**Comment by cogmission** [comment]
> Sun: Prediction is Wed because CLA 1 step prob[2] is highest (???) Here CLA 1 step prob[0] should be highest, by the way.

Sunday's prediction doesn't matter. It should almost never get it right, because we are resetting.

Does that make sense?

**Comment by chessweb01** [comment]
No it doesn't make sense because in my simulation the reset happens on day later.

**Comment by cogmission** [comment]
I don't understand - did you change the code to reset on Tuesday instead of Monday?

**Comment by chessweb01** [comment]
Yes of course. Instead of 
    `if (i == 0 && isResetting) tm.reset(layer.getMemory());`
I put in 
    `if (i == 1 && isResetting) tm.reset(layer.getMemory());`

**Comment by cogmission** [comment]
Read my comment above regarding the record number - you have to set that to 0, when you reset.

**Comment by chessweb01** [comment]
OK, missed that. So just to be clear: recordNum is set to zero right after reset and than gets incremented until the next reset. So in effect there is going to be an offset of one between i and recordNum when I rest on Tuesday, right?

**Comment by cogmission** [comment]
If you start on Monday and reset on Tuesday, the first pattern will have 8 days the rest will have 7. I'm not exactly sure both what to expect or what the effect will be? :-P The record number has to be reset though at the same time. (For the sake of the classifier only)

**Comment by cogmission** [comment]
Closing this as this wasn't really a problem

**Comment by chessweb01** [comment]
We'll see. I'm not convinced, yet. From a mathematical point of view I don't see what it matters at what particular day the reset happens as long as it happens periodically. What is so special about Monday, except that by convention our week starts there?

**Comment by cogmission** [comment]
@chessweb01 Nothing is special about it at all. The classifier just uses the record number to track its "moving window" of data to consider. Nobody is saying any particular day is important, but you have to set the record number to "0" when resetting is all. Has nothing to do with math (outside of simple addition to be able to count back the relevant number of cycles).

There's nothing to be convinced of. Record "0" never has any predictions from the TemporalMemory, and never has corresponding predictions. As a matter of fact, record "0" just happens to correspond with bucket "0" in this case, but the zero'th bucket could be **any** number. 

The only thing that was ever wrong with the code is the fact that the "zero case" isn't handled explicitly so that confusion doesn't arise. People think (including myself at first) that because a zero record is getting added to the activeBitHistory, it needs to therefore be referenced at some point - when **actually** the code just needs to be more explicit about what it is doing so that this confusion doesn't arise.

**Comment by chessweb01** [comment]
Here is my simulation code: i starts at 1, then cycles from 0 to 6, reset occurs always at i = 1, at the same time recordNum (via (int)i-1) is reset to zero.

       `for(double i = 1, x = 0;x < 10000;i = (i == 6 ? 0 : i + 1), x++) {  // USE "X" here to control run length
            if (i == 1 && isResetting) tm.reset(layer.getMemory());
            
            // For 3rd argument: Use "i" for record num if re-cycling records (isResetting == true) - otherwise use "x" (the sequence number)
            runThroughLayer(layer, i + 1, isResetting ? (int)i-1 : (int)x, (int)x);
        }`

Management summary: Nothing has changed. But please take the time to actually study the results, or repeat the simulations for yourself:

First run is with original code in CLAClassifier.java:307. As before, Sunday just doesn't make sense for the reasons stated above.

===== Saturday (6)  - Sequence Num: 9993 =====
CLAClassifier 1 step prob = [0.0, 0.002538001921929813, 0.09818210369554997, 0.05836079875056314, 0.10750843822167225, 0.23585742303126403, 0.49755323437902066]

===== Sunday (7)  - Sequence Num: 9994 =====
CLAClassifier 1 step prob = [0.0, 0.012258043535304453, 0.520157850920085, 0.047007419115190234, 0.05220952528058509, 0.0, 0.3683671611488351]

===== Monday (1)  - Sequence Num: 9995 =====
CLAClassifier 1 step prob = [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]

===== Tuesday (2)  - Sequence Num: 9996 =====
CLAClassifier 1 step prob = [0.0, 0.008767419295208417, 0.49325778314199153, 0.17814012253919656, 0.10657025685810952, 0.10774677492035012, 0.10551764324514397]

===== Wednesday (3)  - Sequence Num: 9997 =====
CLAClassifier 1 step prob = [0.0, 0.004079171586866025, 0.2598760924685099, 0.28913822946447354, 0.1727668141456125, 0.17490916573437681, 0.09923052660016117]

===== Thursday (4)  - Sequence Num: 9998 =====
CLAClassifier 1 step prob = [0.0, 0.003652935512512066, 0.16115942380120954, 0.1788764511798526, 0.2939404962986081, 0.1980037444196309, 0.16436694878818675]

===== Friday (5)  - Sequence Num: 9999 =====
CLAClassifier 1 step prob = [0.0, 0.0013532002244095254, 0.11314306808323268, 0.12604697708293058, 0.14848328699574892, 0.3382599657062002, 0.2727135019074781]

Second run is with the proposed change in CLAClassifier:307 'if(iteration == learnIteration - nSteps || learnIteration - nSteps < 0)'. This is exactly what I expect from a functioning classifier given the temporal memory output (not shown here): 

===== Saturday (6)  - Sequence Num: 9993 =====
CLAClassifier 1 step prob = [0.06791691563243454, 0.0021585283127994407, 0.0859386584662373, 0.05817346208040522, 0.10724434297933515, 0.2349944694763561, 0.44357362305243214]

===== Sunday (7)  - Sequence Num: 9994 =====
CLAClassifier 1 step prob = [0.4157330055327218, 0.008215138858769436, 0.3432964651685829, 0.03821463909402545, 0.042386842409635576, 0.0, 0.1521539089362649]

===== Monday (1)  - Sequence Num: 9995 =====
CLAClassifier 1 step prob = [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]

===== Tuesday (2)  - Sequence Num: 9996 =====
CLAClassifier 1 step prob = [0.1203747076142991, 0.006594117662975054, 0.3980094553364173, 0.17322940172193388, 0.10112849947196628, 0.10749273609997739, 0.09317108209243095]

===== Wednesday (3)  - Sequence Num: 9997 =====
CLAClassifier 1 step prob = [0.024591965897885905, 0.0038540278538903164, 0.25276336440271424, 0.2812528999021233, 0.1641189923481531, 0.17460819728938104, 0.09881055230585203]

===== Thursday (4)  - Sequence Num: 9998 =====
CLAClassifier 1 step prob = [0.028184085542746855, 0.0033991596821378307, 0.1531281609990126, 0.16998135519449797, 0.28388411793627294, 0.1975919020585127, 0.163831218586819]

===== Friday (5)  - Sequence Num: 9999 =====
CLAClassifier 1 step prob = [0.0027165149167234907, 0.0013492089525593202, 0.11296138413041615, 0.1258440153055567, 0.14817662559221736, 0.33727369324169626, 0.2716785578608308]

**Comment by chessweb01** [comment]
@cogmission By the way, in order to reproduce the results above, you gave to run with

`parameters.setParameterByKey(KEY.SYN_PERM_INACTIVE_DEC, 0.01);`
`parameters.setParameterByKey(KEY.SYN_PERM_ACTIVE_INC, 0.1);`

which are the parameters you used in QuickTest.java before all this started with #232

**Comment by chessweb01** [comment]
@cogmission : I guess you are right, after all.

I eventually did a simulation with the following code:

        `for(double i = 1, x = 0;x < 10000;i = (i == 6 ? 0 : i + 1), x++) {  // USE "X" here to control run length
        	if (i == 1 && isResetting) tm.reset(layer.getMemory());
            
        	int recordNum = ((int)i > 0 ? (int)i - 1 : 6); // cycles from 0 to 6
        	runThroughLayer(layer, i + 1, isResetting ? recordNum : (int)x, (int)x);
        }`

and the results are OK. All classifier predictions (Sun->Mon included) make sense. There is no prediction from Mon to Tue due to memory reset and the corresponding slot in CLA 1 step prob stays identical to zero. I guess that settles the issue even for me ;-)

**Comment by cogmission** [comment]
Thank you for not giving up. The code's health is what's important. See you on the next bug? :-)

Cheers, 
David
