### ISSUE TITLE
Possible discrepancy in TemporalMemory.java with nupic/research/temporal_memory.py 

### ISSUE THREAD

**Issue by quinnliu** [numenta/htm.java#246]
@cogmission I don't know if you are basing your TemporalMemory.java implementation off of 
nupic/research/temporal_memory.py but while looking at the both of them I noticed a small difference in Phase 1's if/else statement

TemporalMemory.java line 151 [here](https://github.com/numenta/nupic/blob/master/nupic/research/temporal_memory.py)

```java
/**
     * Phase 1: Activate the correctly predictive cells
     * 
     * Pseudocode:
     *
     * - for each previous predictive cell
     *   - if in active column
     *     - mark it as active
     *     - mark it as winner cell
     *     - mark column as predicted
```

and nupic/research/temporal_memory.py line 238 [here](https://github.com/numenta/nupic/blob/master/nupic/research/temporal_memory.py)

```java
"""
    Phase 1: Activate the correctly predictive cells.
    Pseudocode:
      - for each prev predictive cell
        - if in active column
          - mark it as active
          - mark it as winner cell
          - mark column as predicted
        - if not in active column
          - mark it as an predicted but inactive cell
```

**Comment by cogmission** [comment]
@quinnliu Thanks, yeah they just enhanced the algorithm this week - to purge orphaned dendrites. I haven't had a chance to catch up yet.

**Comment by quinnliu** [comment]
@cogmission Awesome! I've been reading your code and it's really good. You've done some great porting to Java.

**Comment by cogmission** [comment]
@quinnliu thank you very much, that is kind of you to say.

**Comment by cogmission** [comment]
@quinnliu I'm going to take this on now...

**Comment by cogmission** [comment]
Closing this and continuing with #270
