### ISSUE TITLE
SensorFactory implementor must declare itself

### ISSUE THREAD

**Issue by clumsy** [numenta/htm.java#250]
E.g. FileSensor
Using lambdas is fine, but nothing stops from putting the markers for library classes in order for IDE to look them up.

**Comment by cogmission** [comment]
Not sure I understand what you mean? What is it you wish to accomplish?

**Comment by clumsy** [comment]
I'd like to use basic IDE tools to show me existing implementations of SensorFactory, so that we don't end up with several SensorFactory<File> or SensoryFactory<String>.

SensorFactory is declared as FunctionalInterface so that lambda could be passed as an argument - which is fine. Not fine is that somewhere in the library there's a SensorFactory<File> that I need and there's no way of finding that out, but for text search for create() method (which is quite ambiguous to say the least) or check the examples in the hopes to find it.

Marking the existing factories with this interface will not breaking any existing code, whilst make it possible to lookup SensorFactories.

**Comment by cogmission** [comment]
I think that's fine. There are 3 known types of Sensor, which I thought was straight forward? I agree that API isn't "hurt" by explicitly marking them as SensorFactory types - so if you want to add the marker interface, that's fine? Submit a PR with those edits if you like?

**Comment by clumsy** [comment]
Though not sure how to put it better, because due to lambda-like status methods the class cannot be declared as SensorFactory due to name clash. Which means it basically does more than one thing: Sensor itself and a Factory that is capable of creating a new Sensor out of configuration.

Not sure what way is better yet. But I guess I'd rather lookup factories rather than deal with two separate classes.

**Comment by clumsy** [comment]
I'll close the issue.
