### ISSUE TITLE
HTM.java could use a synchronous "step" call that blocks until it returns an "Inference"

### ISSUE THREAD

**Issue by aaronzimmerman** [numenta/htm.java#260]
It isn't clear to me if it would be better to return the inference of the next predicted input, or if it would be better to return what the network predicted the current input would be.   Perhaps both?

**Comment by cogmission** [comment]
Hey Aaron - Yes those are good observations. Fortunately, the Inference returned for each input already contains the [previous prediction](https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/network/Inference.java#L121), So all of that information is available. 

Oh yeah, by "Inference", I meant the actual org.numenta.nupic.network.Inference object. :-)
