### ISSUE TITLE
setup netbeans project

### ISSUE THREAD

**Issue by breznak** [numenta/htm.java#298]
It would be nice to add support for importing into netbeans as well. A project needs to be setup (use info from eclipse) and commit the folder.

**Comment by cogmission** [comment]
@breznak Support for particular IDE's is beyond the scope of this project. I only added a "touch" of Eclipse support because it is what I use, ok?

**Comment by breznak** [comment]
> I only added a "touch" of Eclipse support because it is what I use,

I'd like to have netbeans just for the same convenience reason. Basically that's the 2 big java IDEs, so you'd have that covered. I'll see if I can add NB myself, or if you can help?

**Comment by cogmission** [comment]
I haven't used NB in over 10 years so I'm probably not the best one to help you. My only concern is gradually having to support IDEs. Once we provide a config, we become obligated to support it - not something I'm interested in in the least - and I think it's outside the scope of this project. All Java IDEs must import Java projects which all have the same elements to their config; a root directory; dependencies and dependency locations; and build mechanism - these are all aspects that individual developers should know and manage for their particular IDE choice. Java doesn't require specialized one-off knowledge in contrast to native languages coupled with OS platforms and Java code modules all import the same way. Their source root and dependency locations may differ, but the items to be specified to the IDE, don't vary by project. Therefore I don't feel we should burden the expanse of our support with IDE specific nuance knowledge.

**Comment by cogmission** [comment]
The fact that we're discussing this in an "issue" logged against the entire project, is a case in point. :-)

**Comment by breznak** [comment]
Ok, closing as Won't fix :)
