### ISSUE TITLE
Install problems on linux

### ISSUE THREAD

**Issue by breznak** [numenta/htm.java#300]
Hi, 
I'm trying to install and encounter this problem: 

```
mmm@mmm-U2442:~/devel/nupic/htm.java$ gradle check

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mmm/devel/nupic/htm.java/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating root project 'htm.java'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Env: 
```
Ubuntu 14.04

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ gradle --version

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_79 (Oracle Corporation 24.79-b02)
OS: Linux 3.13.0-63-generic amd64

# i've set JAVA_HOME
$ echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle/
$ ls $JAVA_HOME
bin  COPYRIGHT  db  include  javafx-src.zip  jre  lib  LICENSE  man  README.html  release  src.zip  THIRDPARTYLICENSEREADME-JAVAFX.txt  THIRDPARTYLICENSEREADME.txt
```

Similar: https://github.com/numenta/htm.java/wiki/Eclipse-Setup-Tips I did the `export JAVA_HOME` trick, no help. 

Any idea what can I do? Thanks

**Comment by cogmission** [comment]
@breznak Please don't create issues for your own environment problems. We can take care of this in the gitter forums or on "hackers" mailing list?

**Comment by cogmission** [comment]
I would run "which java" - your path isn't pointing to the 1.8 installation.

Your version seems to be: 1.7.0_79 - 1.8 is the minimum version for this project.

**Comment by breznak** [comment]
> Please don't create issues for your own environment problems. We can take care of this in the gitter forums or on "hackers" mailing list?

Why don't you want to use GH issues for this? I prefer GH over chat is I can work offline on other things. And GH over ML as this msg shows only to the interested people who watch this repo, not spamming everyone on hacker's ML. 

Anyway, is it ok to finish this one here? 

> Gradle seems to be pointing to: 1.7.0_79 - 1.8 is the minimum version for this project.

I'm not sure, does gradle come compiled to a java version? This is how I got it from my distribution.

**Comment by cogmission** [comment]
@breznak Sure we can finish this here since since you are the one and only Breznak ;-) , but I'd like to encourage others to use the other mechanisms in the future.

So we need to understand why gradle is pointing to this other installation. Can you look or search gradle co figs for the text "1.7" or "1.7.0_79"? Do you actually have that version installed? What's the output of "which Java"?

**Comment by cogmission** [comment]
@breznak  Found it!

http://stackoverflow.com/questions/22307516/gradle-finds-wrong-java-home-even-though-its-correctly-set

Let me know if this solves your problem?

**Comment by breznak** [comment]
Thanks :blush: ! 

Fixed the gradle JVM version!, java command was ok: 
```
 update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-8-oracle/jre/bin/java          1076      auto mode
  1            /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java   1061      manual mode
  2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1076      manual mode
```
But somehow "default-java" was pointing elsewhere:
```
$ ls /usr/lib/jvm -l
total 16
lrwxrwxrwx 1 root root   24 Apr 27  2012 default-java -> java-1.7.0-openjdk-amd64
lrwxrwxrwx 1 root root   20 Apr 16  2014 java-1.6.0-openjdk-amd64 -> java-6-openjdk-amd64
lrwxrwxrwx 1 root root   20 Oct 25  2012 java-1.7.0-openjdk-amd64 -> java-7-openjdk-amd64
drwxr-xr-x 7 root root 4096 Aug  6 21:21 java-6-openjdk-amd64
drwxr-xr-x 3 root root 4096 May  9  2014 java-6-openjdk-common
drwxr-xr-x 7 root root 4096 Aug  3 15:18 java-7-openjdk-amd64
drwxr-xr-x 8 root root 4096 Aug 24 15:33 java-8-oracle
```

manually fixing the symlink makes gradle pick up JVM 1.8 correctly:
```
$ gradle --version

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.8.0_60 (Oracle Corporation 25.60-b23)
OS: Linux 3.13.0-63-generic amd64
```

Which moves me to another error: 
```
$ gradle check

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mmm/devel/nupic/htm.java/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating root project 'htm.java'.
> Could not find method jcenter() for arguments [] on repository container.
```

For which I found: https://stackoverflow.com/questions/27470443/could-not-find-method-jcenter-for-arguments-on-repository-container 
..(can you add gradle version check to the requirements?) I'll try to find gradle >1.7 for ubuntu, or theres a workaround in the link.

**Comment by breznak** [comment]
... I've installed a newer gradle from a PPA: http://unixbuzz.com/2014/09/install-gradle-2-1-automation-evolved-ubuntu-14-04-ppa/
And now the build SUCCEEDS! :+1: 

Summary of problems: 
* gradle picked up JVM other than 1.8 (fix default-java symlink)
* gradle version too old (update gradle from PPA)
Btw, 
```
1 warning
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
```

I consider this fixed, thanks for help!

**Comment by breznak** [comment]
(maybe you want to mention this on readme/wiki?)

**Comment by cogmission** [comment]
Sounds good. Thanks! Editing now...

**Comment by cogmission** [comment]
Ok, I added a link to a new wiki page on the README.md under "installation"; and on the wiki pages side bar. :-)

**Comment by breznak** [comment]
I've slightly modified the wiki to include fix for the 2nd problem. Closing the issue. Thanks!

**Comment by cogmission** [comment]
Thank You! :)

On Wed, Sep 2, 2015 at 7:46 AM, breznak <notifications@github.com> wrote:

> I've slightly modified the wiki to include fix for the 2nd problem.
> Closing the issue. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/300#issuecomment-137062611>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io
