### ISSUE TITLE
null-pointer exception in htm.java in version 0.6.1

### ISSUE THREAD

**Issue by rhyolight** [numenta/htm.java#316]
This is bug is reproducible by modifying a two coupled hard-coded values in NetworkTest.java:

* in line 220 of NetworkTest.java, change to "i.getRecordNum() == 82"
* in line 237 of NetworkTest.java, change to "assertEquals(83, lines.size());"

For consistency sake, the 2 lines were modified, if it works, the tests will just pass but the null-pointer exceptions will fire somewhere before the line 220 is reached. 

This bug prevents a modified version of htm.java-examples from running to completion against 0.6.1 of htm.java.

CC @metaml

**Comment by cogmission** [comment]
Why are we opening a bug that is on a previous version and is fixed in the current version? :-P

**Comment by rhyolight** [comment]
All I did was move https://github.com/numenta/nupic/issues/2571 here. If it is invalid, I'll close.

**Comment by metaml** [comment]
Oops, sorry about that. I was confused and just blindly went through the
steps. I'll do better next time :)
-m

**Comment by cogmission** [comment]
@metaml @rhyolight No probs. :+1:
