### ISSUE TITLE
.classpath is missing

### ISSUE THREAD

**Issue by sato-cloudian** [numenta/htm.java#336]
Hi,

The first thing I noticed when I checked out and imported into Eclipse is that src folders are not correctly set. Thus, the entire src folder is set by default.

It would be something like this? But perhaps resources should be added as well.

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
        <classpathentry kind="src" path="src/jmh/java"/>
        <classpathentry kind="src" path="src/test/java"/>
        <classpathentry kind="src" path="src/main/java"/>
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
        <classpathentry kind="output" path="bin"/>
</classpath>
```

Very trivial issue, but helpful if it is set correctly.

Thanks.

**Comment by cogmission** [comment]
@sato-cloudian Thank you very much... I have a thousand things I'm paying attention to, and this one got misconfigured a while back and I never got back on it. 

please see #337

**Comment by cogmission** [comment]
@rhyolight Simple addition of .classpath file. Going to merge this one.

**Comment by sato-cloudian** [comment]
Thanks, confirmed.

**Comment by cogmission** [comment]
Thank YOU...
