### ISSUE TITLE
Change two private methods to protected in Layer.java

### ISSUE THREAD

**Issue by fergalbyrne** [numenta/htm.java#340]
I'm looking at adding paCLA to htm.java using as little new code as possible. I want to inherit from Layer, SpatialPooler and TemporalMemory. In Layer, I just need to override spatialInput() and temporalInput(), but they're marked as private.

**Comment by cogmission** [comment]
Cool!
Its fine to go ahead and change those to protected or public which ever you need.

**Comment by fergalbyrne** [comment]
Cool, I've added the initial hack to make PALayer, PASpatialPooler. `gradle check` works fine, so will PR.
