### ISSUE TITLE
DateEncoder creates spurious anomalies due to sudden shifts (eg at midnight)

### ISSUE THREAD

**Issue by fergalbyrne** [numenta/htm.java#358]
![Example of Spurious Anomalies](http://puu.sh/loHhg/2af0a99560.png)

@JonnoFTW is reporting big anomalies across many of his sensors at midnight every night (see http://puu.sh/loHhg/2af0a99560.png for a plot). There is no anomalous traffic to explain this, and it repeats every night. He is using the standard date encoder, which shifts all its bits at midnight every night. This is causing a dramatic enough shift in the SP output that the columnar representation cannot be predicted by columns over-sensitive to day-of-week bits.

The fix is to add an hourOfWeek encoder to the DateEncoder, which is just a copy of the timeOfDay encoder with max set to 168 instead of 24. I'll add this in and do a PR.

**Comment by cogmission** [comment]
:+1:  A very welcome addition...!
