### ISSUE TITLE
Support for running test cases from Intellij Idea IDE

### ISSUE THREAD

**Issue by mandarx** [numenta/htm.java#388]
Intellij Idea IDE is unable to run junits, because the org.openjdk.jmh dependency is not available in the classpath. This dependency is available in eclipse, as part of the .classpath file. It can be declared as a dependency in maven pom.xml, so that it is available on all IDE's. 

For instance, when the test class org.numenta.nupic.network.LayerTest is executed from Intellij Idea, we see the following error, indicating that classes from jmh library, were not found in the classpath.

<img width="788" alt="screen shot 2016-01-31 at 5 12 59 pm" src="https://cloud.githubusercontent.com/assets/77350/12706705/eeb345d4-c83e-11e5-87c1-a621edcdd0f8.png">

A fix is available as part of the PR #387 

Cc. @cogmission

**Comment by cogmission** [comment]
@mandarx Great! Thanks for doing this. When @rhyolight gets in to work tomorrow, he'll probably be able to take a look at this and approve your CL submission, then this issue can be assigned to you and we can then merge your PR! :+1:

**Comment by mandarx** [comment]
Thanks @cogmission !
