### ISSUE TITLE
MetricsTraceTest.java failes due to JVM using local decimal punctuation

### ISSUE THREAD

**Issue by Setus** [numenta/htm.java#394]
Here in Norway (entire Europe I guess), the JVM seems to prefer to use commas for decimal punctuation as opposed to dots (4,5 instead of 4.5), which causes the aforementioned test to fail when it's expecting results using dots. I tried to do a pull request just earlier, but it seems the build crashed when I tried to submit my change (and I wasn't a member yet)
public String prettyPrintDatum(Metric datum) {
        return String.format(Locale.US, "min: %.2f, max: %.2f, sum: %.2f, mean: %.2f, std dev: %.2f", 
            datum.min, datum.max, datum.sum, datum.mean, datum.standardDeviation);
 }
In addition, the build seemed to complain a lot about gradle failing. Personally, I've had to install gradle 2.10 to make shadowjar work.

**Comment by cogmission** [comment]
@Setus What version of Gradle were you using before installing 2.10 ?

**Comment by cogmission** [comment]
The CL will first have to be accepted by @rhyolight (Matt Taylor - the flag bearer and director of open source for Numenta) - you should get to know that name (and him, he's a great guy).

**Comment by Setus** [comment]
Before I downgraded to Gradle 2.10, I tried using the latest 2.11 version, but it didn't work because of some shadowjar issue.

I have already signed the Contributor's License and become a Numenta member according to Github I think.

Ok, I'll do what you explained. No problems ;)

**Comment by cogmission** [comment]
The shadow jar issue was solved a couple of days ago (should have been) by [this](https://github.com/numenta/htm.java/pull/391) pull request? I guess I should "push" the snapshot up to maven central...

**Comment by cogmission** [comment]
@Setus you can go ahead and resubmit your PR now?
