### ISSUE TITLE
OpenJDK build tests fail

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#403]
This issue is an attempt to fix htm.java on OpenJDK which produces some test failures...

**Comment by EronWright** [comment]
Please reopen so that I may make additional fixes related to this issue.

**Comment by cogmission** [comment]
@EronWright Ok it's reopened

**Comment by cogmission** [comment]
@EronWright I see you already addressed the issue, so I'm closing this. I forgot to apply the fix to PALayerTest as well as LayerTest. (I didn't see that it said "PA", huh boy - and here I thought my fix didn't work!)
