### ISSUE TITLE
Pass the FST configuration to the HTMObjectInput/HTMObjectOutput 

### ISSUE THREAD

**Issue by EronWright** [numenta/htm.java#418]
I notice that `FSTObjectInput` has an overloaded constructor to take the `FSTConfiguration`.    I think the `SerializerCore` should pass the `fastSerialConfig` to the HTM input and output classes.    The current behavior is that the default config is used.

**Comment by cogmission** [comment]
Then are you suggesting that there be a way to pass in a FSTConfiguration of your own?

**Comment by cogmission** [comment]
@EronWright I see, that way we prevent 2 from being created... Makes sense! Thanks!

**Comment by cogmission** [comment]
👍 done.

**Comment by cogmission** [comment]
Fixed in https://github.com/numenta/htm.java/pull/419
