### ISSUE TITLE
`CategoryEncoder` documentation needs updated

### ISSUE THREAD

**Issue by Hopding** [numenta/htm.java#424]
The javadoc comment for [`CategoryEncoder`](https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/encoders/CategoryEncoder.java) needs to be updated. Right now it says:
>The SDRCategoryEncoder (not yet implemented in Java)...

which is incorrect. The [`SDRCategoryEncoder`](https://github.com/numenta/htm.java/blob/38f4a2c2ebae5463ef30bb04cac0b241110a962d/src/main/java/org/numenta/nupic/encoders/SDRCategoryEncoder.java) is indeed implemented in Java, now.

**Comment by cogmission** [comment]
I just merged on master... you'll have to update your master and merge it into your branch before PR submission - Just a heads up...

```git fetch upstream master```
```git checkout <your current work branch not master>```
```git merge upstream/master```

if you don't yet have upstream specified see this...  https://help.github.com/articles/syncing-a-fork/

**Comment by cogmission** [comment]
Also you'll need to fill out one of these to become legit :-P
http://numenta.org/licenses/cl/

**Comment by Hopding** [comment]
Thanks @cogmission, I think I did everything right, haha. Lots of work for a one line fix, but I guess you gotta keep everything neat and tidy :smile:

**Comment by cogmission** [comment]
@Hopding Did you fill out the Contributor's License?

**Comment by Hopding** [comment]
@cogmission yes I did. I haven't yet notified Matt, I assumed he would receive a notification about it. I suppose I'll shoot him a message since he hasn't confirmed it yet(?).
