### ISSUE TITLE
Anomalous Anomaly production for NAB

### ISSUE THREAD

**Issue by fergalbyrne** [numenta/htm.java#432]
Discussed in this [NAB PR](https://github.com/numenta/NAB/pull/237). @BoltzmannBrain reports that running this PR on NAB, the raw anomaly score coming out of HTM.java is not what you would expect if HTM.java was matching NuPIC. It's possible that the divergence has something to do with the fact that NuPIC's raw anomaly score is derived by comparing directly the active columns in the SP and the previously predicted columns in the TM, while the raw anomaly score in HTM.java is produced using the ManualInput which is mutated by various Func's.
Perhaps we need some isolated testing of these interactions, to make sure that the ManualInput paradigm is not introducing some duplication of mutation steps, and causing a semantic error in the calculations.

**Comment by cogmission** [comment]
This has been solved in [NAB](https://github.com/numenta/NAB/pull/237) and resolved in HTM.Java at [this PR 484](https://github.com/numenta/htm.java/pull/484)
