### ISSUE TITLE
NAPI: Layer.java - Dynamic public accessor fields need vetting or removal...

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#442]
The public accessor fields on Layer.class are constantly overwritten and not guaranteed to be consistent with the state "seen" by any Observable listener (Observer/Subscriber/Action) at any single point in time; and so therefore can be misleading.

Any fields which can not be thoroughly corroborated should be removed because they aren't used internally for processing anyway.

**Comment by fergalbyrne** [comment]
I'd suggest removing all the fields which "appear to store" state belonging to sensors, SP, TM etc. You could replace anything currently using them with eg. getTemporalPooler().getXXX().
