### ISSUE TITLE
Use Robust Approach For Comparing Class Tokens

### ISSUE THREAD

**Issue by Hopding** [numenta/htm.java#513]
Right now, the `Classifier` type `Class` tokens in `Layer.java` are compared using the `==` operator. This is unlikely to be e problem since the comparison is being done on a `Class` object, and there is usually only one loaded in the classloader. But, in the event that multiple classloaders are used, it could fail to properly match the `Class` tokens. A better approach would be to use the [`Class.isAssignableFrom`](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#isAssignableFrom(java.lang.Class)) method.

**Comment by cogmission** [comment]
Cool. I see you decided to go through with it... Ok. 👍
