### ISSUE TITLE
htm.java needs a RandomDistributedScalarEncoder

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#85]
This class and test should be created to follow the same idioms and structure as the Encoder.java and ScalarEncoder.java class. The CategoryEncoder, can be used as an example.

**Comment by connollyst** [comment]
Hi @anubhavchaturvedi,

This ticket is assigned to you and in progress. I don't see any other 'beginner' tickets I can play with to familiarize myself with ``htm.java`` so am going to take a stab at this. Let me know if you've already made some progress here.

Cheers,
Sean

**Comment by anubhavchaturvedi** [comment]
Hi @connollyst ,
My apologies for not seeing this earlier. Most of my communication on this was on gitter. 
I had implemented it earlier but there was one test failing. Now all the tests are passing.

https://github.com/anubhavchaturvedi/htm.java/tree/RDSE

**Comment by connollyst** [comment]
Hmmm, shame we didn't communicate this better a week back.

**Comment by cogmission** [comment]
Did you not see that it was already assigned? I had been away for a month so my assumption was that the two of you had worked it out, because there was another issue which two developers had decided to collaborate on and the discussion had taken place before my break - so that was fresh on my mind.
Again, I'm sorry - but this is why we track these and assign them. I know that still is disappointing for you, but the process is pretty clear - and the issue is marked as assigned?

**Comment by cogmission** [comment]
@connollyst Talk to Anubhav, I believe he is willing to collaborate, and maybe you can take the best of both of your work?

**Comment by connollyst** [comment]
Hi @cogmission,

No worries. The implementations are both ports of the original code so are nearly identical. I'll revert my changes.

-Sean

**Comment by cogmission** [comment]
The method that uses your update of the ArrayUtils method, I think would be good to keep? I know I would like to have that change in the code if its ok with you to merge that in?

**Comment by anubhavchaturvedi** [comment]
@connollyst , would you like to collaborate and be the author along with me. I would like to use your documentation and we can figure out where we both can benefit from each other's implementation and submit a final encoder.

**Comment by connollyst** [comment]
@anubhavchaturvedi as long as the task is resolved, all is well. A double merge would probably be more trouble than it's worth. When your branch pulls onto master I'll have a look through if there's anything I did worth re-implementing.

-Sean
