### ISSUE TITLE
htm.java needs a DateEncoder

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#87]
This class and test should be created to follow the same idioms and structure as the Encoder.java and ScalarEncoder.java class. The CategoryEncoder, can be used as an example.

**Comment by utensil** [comment]
Happy new year,  @cogmission !

Thanks for your consideration and my mom is better now.

After the long delay, I've finally find a piece of continuous time to work on the `DateEncoder` and opened #141  for discussion. Hope it's still in time.
