### ISSUE TITLE
htm.java needs DeltaEncoder

### ISSUE THREAD

**Issue by cogmission** [numenta/htm.java#91]
This class and test should be created to follow the same idioms and structure as the Encoder.java and ScalarEncoder.java class. The CategoryEncoder, can be used as an example.

Should use only the Joda Date Library

**Comment by connollyst** [comment]
Hi all, happy new year!

I'm looking to get my feet wet with ``htm.java`` and help out where I can. I see this ticket is still open and has the "help wanted" label, though it looks as though you've made some progress @sambitgaan. What is the current status of this ticket? Can I help in any way?

Cheers,
Sean

**Comment by sambitgaan** [comment]
Hi Sean,

I also wish you a best happy, cheerful new year.
I am middle of something. What I will do is that I will try to sum up and
commit it to my branch.
Then I will let you know those portions, where you can start adding. In
that we both can complete it.
Give me a day or two, I will get back to you soon.

Regards,
Sambit Gaan

**Comment by connollyst** [comment]
Cool. I've started working on another ''Encoder'' so that'll keep me busy for a few days. Let me know how I can help.

**Comment by cogmission** [comment]
Hi Sean! and Welcome!

Please let me know if you would like assistance with anything or if you
have questions please feel free to hit me up here or in
https://gitter.im/numenta/public

Cheers!

David

On Thu, Jan 8, 2015 at 4:21 AM, Sean Connolly <notifications@github.com>
wrote:

> Cool. I've started working on another ''Encoder'' so that'll keep me busy
> for a few days. Let me know how I can help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/91#issuecomment-69160870>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by connollyst** [comment]
Hey @sambitgaan, any progress on this? If I can help in any way, please push something to your repo, let me know, and I'll fork it.

Cheers,
Sean

**Comment by sambitgaan** [comment]
Hi Sean,
I was bug down by some of urgent things at my work.
Definitely I will try to push something to my repo and let you know so that
you can fork it.

Regards,
Sambit

**Comment by sambitgaan** [comment]
Hi Sean,

Currently, I am working on the following classes.

AdaptiveScalarEncoder
AdaptiveScalarEncoderTest
DeltaEncoder
DeltaEncoderTest

I am nearly done with Adaptive* classes, but I am midway through the rest
two classes.
Also I have not incorporated the recent changes for logging.

If you have some bandwidth then please add the logging mechanism for the
classes and let me know once you push something to your branch so that I
can merge it.

Regards,
Sambit
